# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.162.0/containers/alpine/.devcontainer/base.Dockerfile

FROM sridca/neuron

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apk update \
#     && apk add --no-cache <your-package-list-here>
